language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
- npm run build
- npm run lint-functions
notifications:
  slack:
    secure: X5M5atIaGOaBdkMWwsc8o9m9wXb4Tkc4Su74Rfyx65h/bMlTEx1b0+KMKl2+Ne/v2REobNcgVBlVojyQds4tePErINStwS522CZeve/5/WWnoBPkv+zFNaWldG0SCxqYsBp9ytZku3NHjTQY+Fro+iLNGjwiw7j1pzrhapIDBBlrfxuKusba929mwYjwvpe/DP3lrdSBP6ea9WrQBab3xbeTg0WUP2Cc3OHX5IfaGYv/7hgu17PEkrECO5mH871sX5rAVRsiwn1MnLsA9p3oEAQEIeyEwmvSXC3WK61G388hyW5c+evUDoMgkXOhK/5meAKyaegjudRDFqXNpvPXX1VQM2gOHpLio31ahwGC7KmCZ09bE6TCUayOYY1rere/OPgetauoPVduMtIoAkolr4XRrdLKhMl2/LLH0uTUWG3733Rnht5PUw7nwe4Hgw5lr1wFChOHVDZzveuqiBDO4lluvX4uADFVGqckiGxEDbRDiEheWm9uvXnKBSyNkqlvE5cZI4xKifBsgIPkPlsOhMRpQrd1jHNWshY2JtY9tLJ9Zm2BUvNRTfAFuxt2HU5h4YfmkpRjXG7DzWr18Cl5BzRVMRFEaXC5O/kC0MkETLk+52uqF6cVUHmqJ/No4eWr9nMPvhkZBfkVvRiKSoexL/dkcvcis2ZwoQ3V8ch7vW8=